# Generated by Django 4.2.4 on 2023-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_askstory_api_id_alter_askstory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="askstory",
            name="time",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="time",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="poll",
            name="time",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="story",
            name="time",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
