# Generated by Django 4.2.4 on 2023-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_askstory_time_alter_comment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
