# Generated by Django 4.2.4 on 2023-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_job_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="askstory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="poll",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
